-- ==========================
-- fichier : viderbase.sql
-- base : BILLETERIE
-- auteur(s) : Nicolas DOUSSON
-- auteur(s) : Maxime LAFARIE
-- date : 07/01/14
-- role : 
-- projet : 
-- ==========================